Backend/VisualSculptingClassroom/VisualSculptingClassroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('users/', include('users.urls', namespace='users')),
    path('classrooms/', include('classrooms.urls', namespace='classrooms')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/VisualSculptingClassroom/classrooms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve

from classrooms.views import classrooms_list, classroom_creation, class_list, enter_classroom, leave_classroom, delete_user, cube, works, work_adding, work_big, putting_mark, download, delete

app_name = "classrooms"

urlpatterns = [
    path('classrooms_list/', classrooms_list, name="classrooms_list"),
    path('classroom_creation/', classroom_creation, name="classroom_creation"),
    path('class_list/<int:classroom_key>/', class_list, name="class_list"),
    path('enter_classroom/<str:user_login>/', enter_classroom, name="enter_classroom"),
    path('leave_classroom/<int:classroom_key>/', leave_classroom, name="leave_classroom"),
    path('delete_user/<int:delete_key>/<str:deleted_username>/', delete_user, name="delete_user"),
    path('cube/', cube, name="cube"),
    path('works/<str:user_login>/<int:class_key>/', works, name="works"),
    path('work_adding/<int:classroom_key>/', work_adding, name="work_adding"),
    path('work_big/<str:author_login>/<int:classroom_key>/<int:work_pk>/', work_big, name="work_big"),
    path('putting_mark/<str:student_login>/<int:class_k>/<int:work_pk>/', putting_mark, name="putting_mark"),
    path('download/<int:work_id>/', download, name="download"),
    path('delete/<int:work_id>/<int:cl_k>/', delete, name="delete"),
]

Backend/VisualSculptingClassroom/users/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import login, registration, logout, profile
app_name = 'users'

urlpatterns = [
    path('login/', login, name = 'login'),
    path('registration/', registration, name = 'registration'),
    path('logout/', logout, name= 'logout'),
    path('profile/<int:user_id>/', profile, name='profile'),
]

Backend/VisualSculptingClassroom/classrooms/models.py
from django.db import models
from random import randint
from django.templatetags.static import static
from users.models import User

# Create your models here.

class Classroom(models.Model):
    name = models.CharField(max_length=256)
    creator = models.CharField(max_length=256)
    key = models.IntegerField()

class ClassroomListQuerySet(models.QuerySet):
    pass

class ClassroomList(models.Model):
    classroom = models.ForeignKey(to=Classroom, on_delete=models.CASCADE)
    member = models.ForeignKey(to=User, on_delete=models.CASCADE)
    objects = ClassroomListQuerySet.as_manager()
    def medium_mark(self):
        classroom=self.classroom
        student=self.member
        mark_objects = Mark.objects.filter(student=student, classroom=classroom)
        marks = list(mark_objects.values_list("value", flat=True))
        summary = 0
        for mark in marks:
            summary += mark
        if marks:
            return summary / len(marks)
        else:
            return "нет оценок"
class Work(models.Model):
    name = models.CharField(max_length=256)
    classroom = models.ForeignKey(to=Classroom, on_delete=models.CASCADE)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    file_model = models.FileField(null=False, upload_to='models', default=static('img/default.gltf'))
    file_sup = models.FileField(null=True, upload_to='models')
    file_textures = models.FileField(null=True, upload_to='models/textures')

class Mark(models.Model):
    values = ((5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'))
    value = models.IntegerField(choices=values, default=5)
    student = models.ForeignKey(to=User, on_delete=models.CASCADE)
    teacher = models.CharField(max_length=256)
    classroom = models.ForeignKey(to=Classroom, on_delete=models.CASCADE)
    project = models.ForeignKey(to=Work, on_delete=models.CASCADE, default=0)

Backend/VisualSculptingClassroom/classrooms/forms.py
from django.forms import ModelForm
from django import forms
from random import randint

from classrooms.models import Classroom, Work, Mark

class ClassroomCreationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'type':'text',
        'name':'text_name',
        'placeholder':'Название класса',
        'style':"width: 90%; line-height: 28px;"
    }))
    key = forms.IntegerField(widget=forms.TextInput(attrs={
        'style':"display:none;",
        "readonly": "true"
    }))
    creator = forms.CharField(widget=forms.TextInput(attrs={
        'style':"display:none;",
        "readonly": "true"
    }))
    class Meta:
        model = Classroom
        fields = ('name','key','creator')
class EnterClassroom(forms.Form):
    key = forms.IntegerField(max_value= 100000000, widget=forms.TextInput(attrs={
        "type": "text",
        "name": "text_name",
        "placeholder": "Код класса",
        "style": "width: 50%; line-height: 28px;"
    }))

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class FileFieldForm(forms.Form):
    file_field = MultipleFileField()

class WorkUploadForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'type':'text',
        'name':'text_name',
        'placeholder':'Название работы',
        'style':"width: 50%; line-height: 28px;"
    }))
    file_model = forms.FileField(widget=forms.ClearableFileInput(attrs={
        'type':'file',
    }))
    file_sup = MultipleFileField(required=False, widget=MultipleFileInput(attrs={
        'type':'file',
        'multiple': True
    }))
    file_textures = MultipleFileField(required=False, widget=MultipleFileInput(attrs={
        'type': 'file',
        'multiple': True
    }))
    class Meta:
        model = Work
        fields = ('name', 'file_model', 'file_textures', 'file_sup')
class MarkPuttingForm(forms.ModelForm):
    value = forms.Select(attrs={
        "font-size": "15px",
    })
    class Meta:
        model = Mark
        fields = ('value',)

Backend/VisualSculptingClassroom/classrooms/views.py
import random
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static
from django.http import JsonResponse
from django.conf import settings
import os
from django.http import FileResponse

from classrooms.forms import ClassroomCreationForm, EnterClassroom, WorkUploadForm, MarkPuttingForm
from users.models import User
from classrooms.models import Classroom, ClassroomList, Work, Mark
# Create your views here.
@login_required

def cube(request):
    context= {
        "model_path" : static("img/scene.gltf")
    }

    return render(request, 'classrooms/index.html',context)

def classrooms_list(request):
    context = {
        'title': 'Список классов',
        'user': request.user,
        'classes': list(ClassroomList.objects.all())
    }
    return render(request, 'classrooms/classrooms_list.html', context)

def classroom_creation(request):
    if request.method == 'POST':
        form = ClassroomCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            real_key = form.cleaned_data['key']
            ClassroomList.objects.create(member=request.user, classroom=Classroom.objects.get(key=real_key))
            return HttpResponseRedirect(reverse('classrooms:classrooms_list'))
    else:
        keys = Classroom.objects.values_list("key")
        keys_list = list(keys)
        random_key = random.randint(10000000, 99999999)
        while random_key in keys_list:
            random_key = random.randint(10000000, 99999999)
        initial_data = {'key': random_key, 'creator': request.user.username}
        form = ClassroomCreationForm(initial=initial_data)
    context = {
        'form': form,
        'title': 'Создание класса'
    }
    return render(request, 'classrooms/classroom_creation.html', context)

def class_list(request, classroom_key):
    if request.user.username == Classroom.objects.get(key=classroom_key).creator:
        f = 1
    else:
        f = 0
    students = []
    for cl in ClassroomList.objects.all():
        if cl.classroom.key == classroom_key:
            students.append(cl)
    context = {
        'title': 'Список класса',
        'members': students,
        'is_admin':f,
        'name_of_admin':Classroom.objects.get(key=classroom_key).creator,
        'classroom_key': classroom_key,
        'marks':Mark.objects.all()
    }
    return render(request, 'classrooms/class_list.html', context)

def enter_classroom(request, user_login):
    if request.method == "POST":
        form = EnterClassroom(request.POST)
        if form.is_valid():
            key_user = form.cleaned_data['key']
            for real_key_n in Classroom.objects.values_list('key'):
                real_key = real_key_n[0]
                if key_user == real_key:
                    new_member = User.objects.get(username=user_login)
                    members = ClassroomList.objects.filter(member=request.user, classroom=Classroom.objects.get(key=real_key))
                    if not members.exists():
                        ClassroomList.objects.create(member=new_member, classroom=Classroom.objects.get(key=real_key))
                        return HttpResponseRedirect(reverse('classrooms:classrooms_list'))
                    break
                else:
                    pass
                        #Действие если пользователь уже в классе
    else:
        form = EnterClassroom()
    context = {
        'title': 'Вход в класс',
        'form': form,
        'user': request.user,
    }
    return render(request, 'classrooms/enter_classroom.html', context)

def leave_classroom(request, classroom_key):
    class_to_del = Classroom.objects.get(key=classroom_key)
    if class_to_del.creator == request.user.username:
        Classroom.objects.filter(key=classroom_key).delete()
    else:
        ClassroomList.objects.filter(classroom=class_to_del, member=request.user).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def delete_user(request, delete_key,deleted_username):
    classroom_d = Classroom.objects.get(key=delete_key)
    member_d = User.objects.get(username=deleted_username)
    ClassroomList.objects.filter(classroom = classroom_d, member = member_d).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def works(request, user_login, class_key):
    user = User.objects.get(username=user_login)
    context = {
        'title': 'Работы ученика',
        'user': user,
        'role': request.user.roles,
        'class_key': class_key,
        'looking': request.user.username,
        'all_works':Work.objects.filter(author=user, classroom=Classroom.objects.get(key=class_key))
    }
    return render(request, 'classrooms/works.html', context)

def work_big(request, author_login, classroom_key, work_pk):
    author = User.objects.get(username=author_login)
    cl_list = ClassroomList.objects.filter(classroom=Classroom.objects.get(key=classroom_key))
    members = list(cl_list.values_list('member'))
    for i in range(len(members)):
        members[i] = members[i][0]
    teachers = []
    for teacher in User.objects.filter(roles='teacher'):
        if teacher.pk in members:
            teachers.append(teacher)
    work = Work.objects.get(pk=work_pk)
    loge = User.objects.get(username=author_login)
    cl = Classroom.objects.get(key=classroom_key)
    m = Mark.objects.filter(teacher=request.user.username, student=loge, classroom=cl, project=Work.objects.get(pk=work_pk))
    m1 = Mark.objects.filter(student=loge, classroom=cl, project=Work.objects.get(pk=work_pk))
    if m.exists():
        m = True
    else:
        m = False
    if request.method == "POST":
        form = MarkPuttingForm(data=request.POST)
        if form.is_valid():
            mark = form.cleaned_data['value']
            Mark.objects.create(value=mark, student = loge, teacher = request.user.username, classroom = cl, project = Work.objects.get(pk=work_pk))
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        else:
            print(form.errors)
    else:
        form = MarkPuttingForm()
    marks_objects = Mark.objects.filter(project=work)
    marks = list(marks_objects.values_list("value", flat=True))
    summary = 0
    for mark in marks:
        summary += mark
    if marks:
        work_medium_mark = summary / len(marks)
    else:
        work_medium_mark = "нет оценок"
    context = {
        'title': 'Работы ученика',
        'author': author,
        'user': request.user,
        'teachers':teachers,
        'work': work,
        'format': work.file_model.name[-4:],
        'cl': Classroom.objects.get(key=classroom_key),
        'm1':m1,
        'm':m,
        'form':form,
        'a_l':author_login,
        'c_k':classroom_key,
        'work_pk':work_pk,
        'work_medium_mark':work_medium_mark,
    }
    return render(request, 'classrooms/work_big.html', context)


def work_adding(request, classroom_key):
    if request.method == "POST":
        user = request.user
        place = Classroom.objects.get(key=classroom_key)
        form = WorkUploadForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            title = form.cleaned_data['name']
            obj = form.cleaned_data['file_model']
            Work.objects.create(name=title, classroom=place, author=user, file_model=obj)
            return HttpResponseRedirect(reverse('classrooms:works', kwargs={'user_login':user.username, 'class_key':classroom_key}))
        else:
            print(form.errors)
    else:
        form = WorkUploadForm()
    context = {
        'form': form,
        'title': 'Добавление работы',
        'key':classroom_key
    }
    return render(request, 'classrooms/work_adding.html', context)

def putting_mark(request, student_login, class_k, work_pk):
    if request.method == "POST":
        form = MarkPuttingForm(data=request.POST)
        loge = User.objects.get(username=student_login)
        cl = Classroom.objects.get(key=class_k)
        m = Mark.objects.filter(teacher=request.user.username, student=loge, classroom=cl)
        m1 = m
        if m.exists():
            m = True
        else:
            m = False
        if form.is_valid():
            mark = form.cleaned_data['value']
            Mark.objects.create(value=mark, student = loge, teacher = request.user.username, classroom = cl, project = Work.objects.get(pk=work_pk))
            return HttpResponseRedirect(reverse('classrooms:work_big', kwargs={'author_login':loge.username, 'classroom_key':class_k, "work_pk":work_pk}))
        else:
            print(form.errors)
    else:
        form = MarkPuttingForm()
    context = {
        'form':form,
        'user':request.user,
        'm':m,
        'm1':m1
    }
    return render(request, 'classrooms/work_big.html', context)

def download(request, work_id):
    response = FileResponse(open(Work.objects.get(pk=work_id).file_model.path, "rb"))
    return response
def delete(request, work_id, cl_k):
    Work.objects.filter(pk = work_id).delete()
    return HttpResponseRedirect(reverse('classrooms:works', kwargs={'user_login':request.user.username, 'class_key':cl_k}))

Backend/VisualSculptingClassroom/classrooms/templates/classrooms/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{{ title }}</title>
    <LINK TYPE="text/css" REL="stylesheet" HREF="{% static 'css/1.css' %}">
	<link rel="shortcut icon" href="#">
</head>
<body vlink="#003366">

       <div class="header_lag">
		<div id="Div1">
                Virtual Sculpting Classroom
		</div>
		<div id="buttonsright">
			<a href="{% url 'users:profile' user.pk %}">Мой профиль</a>
			<a href="{% url 'classrooms:classrooms_list' %}">Классы</a>
            <a href="{% url 'users:logout' %}">Выйти</a>

		</div>
	</div>
	{% block content %}
	{% endblock %}
</body>
</html>

Backend/VisualSculptingClassroom/classrooms/templates/classrooms/class_list.html
{% extends 'classrooms/base.html' %}

{% block content %}
    <CENTER>
        <! ЛЕВАЯ СТОРОНА -->
        <div class="Ramka1 dop2 not_Ramka1 not_background-image">
            <b>Ученики</b><br>
        {% for person in members %}
            {% if person.member.roles == 'student' %}
            <div class="header_lag  widht_95  Ellipse1">
                <div id="Div2">
                    {{ person.member.first_name }} {{ person.member.last_name }}
                </div>
                <div id="Div15">
                    Средний балл: {{ person.medium_mark }}
                </div>
                <div id="Div3">

                    <a href="{% url 'classrooms:works' user_login=person.member.username class_key=classroom_key %}">Работы</a>
                    {% if is_admin and person.member.username != name_of_admin %}
                    <a href="{% url 'classrooms:delete_user' delete_key=classroom_key deleted_username=person.member.username %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        {% endfor %}
        </div>

        <! ПРАВАЯ СТОРОНА -->
        <div class="Ramka1 dop2 not_Ramka1 not_background-image">
            <b>Учителя</b><br>
        {% for person in members %}
            {% if person.member.roles == 'teacher' %}
            <div class="header_lag  widht_95  Ellipse1">
                <div id="Div2">
                    {{ person.member.first_name }} {{ person.member.last_name }}
                </div>
                <div id="Div3">
                    {% if is_admin and person.member.username != name_of_admin %}
                    <a href="{% url 'classrooms:delete_user' delete_key=classroom_key deleted_username=person.member.username %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        {% endfor %}
        </div>
    </CENTER>
{% endblock %}

Backend/VisualSculptingClassroom/classrooms/templates/classrooms/classroom_creation.html
{% extends 'classrooms/base.html' %}
{% block content %}
<form action = "{% url 'classrooms:classroom_creation' %}" method = "POST">
 {% csrf_token %}
 <div class="Ramka1">
            <B><p>Создание класса</p></B>
            <p>{{ form.name }}</p>
            <p>{{ form.key }}</p>
            <p>{{ form.creator }}</p>
            <p><button class="favorite styled" type="submit">Создать</button></p>
        </div>
</form>
{% endblock %}

Backend/VisualSculptingClassroom/classrooms/templates/classrooms/classrooms_list.html
{% extends 'classrooms/base.html' %}
{% block content %}
	<center>
	<b>Ваши классы</b>
	</center>
	{% for cl in classes %}
		 {% if user.username == cl.member.username %}
     		<div class="header_lag  widht_70 margin_auto Ellipse1">
				<div id="Div2">
					<a href = "{% url 'classrooms:class_list' cl.classroom.key %}">{{ cl.classroom.name }}</a>
				</div>
				<div id="Div3" title = "Сообщите его, чтобы другие могли подключиться">
					Код класса: {{ cl.classroom.key }}
					{% if user.username == cl.classroom.creator %}
					<a href="{% url 'classrooms:leave_classroom' cl.classroom.key %}">Удалить</a>
					{% else %}
					<a href="{% url 'classrooms:leave_classroom' cl.classroom.key %}">Покинуть</a>
					{% endif %}
				</div>
			</div>
		{% endif %}
	{% endfor %}
    <div class="header_lag  widht_70 margin_auto Ellipse1">
		<div id="Div8">
			<a href="{% url 'classrooms:classroom_creation' %}">
                     Создать новый класс
			</a>
		</div>
	</div>

     <div class="header_lag  widht_70 margin_auto Ellipse1">
		<div id="Div9">
			<a href="{% url 'classrooms:enter_classroom' user.username %}">
                    Присоединиться к классу
			</a>
		</div>

	</div>
{% endblock %}

Backend/VisualSculptingClassroom/classrooms/templates/classrooms/enter_classroom.html
{% extends 'classrooms/base.html' %}

{% block content %}
    <form action = "{% url 'classrooms:enter_classroom' user.username %}" method = "POST">
        {% csrf_token %}
        <div class="Ramka1">
            <B><p>Вход в класс</p></B>
            {{ form.key }}
            <p><button class="favorite styled" type="submit">Войти</button></p>
        </div>
    </form>
{% endblock %}

Backend/VisualSculptingClassroom/classrooms/templates/classrooms/work_big.html
{% extends 'classrooms/base.html' %}
{% load static %}
{% block content %}
    <CENTER>
         <b>{{ work.name }}:</b><br>

        <! ЛЕВАЯ СТОРОНА -->
        <div class="Ramka1 dop2 not_Ramka1 not_background-image new-width">
            <div class="canvas">
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/build/three.min.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/examples/js/controls/OrbitControls.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/examples/js/loaders/GLTFLoader.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/examples/js/loaders/OBJLoader.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/examples/js/loaders/FBXLoader.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/examples/js/loaders/ColladaLoader.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/three@0.139.0/examples/js/loaders/MTLLoader.js"></script>
                <script src="https://unpkg.com/fflate@0.8.2"></script>
                <script src="https://cdn.jsdelivr.net/npm/fflate@0.8.2/umd/index.js"></script>

                <script type="module">

                    let scene, camera, renderer, controls, objectToRotate;

                    init();
                    animate();

                    function init() {
                        // Scene
                        scene = new THREE.Scene();

                        // Camera
                        const aspectRatio = 1 / 1; // Aspect ratio 16:9
                        camera = new THREE.PerspectiveCamera(75, aspectRatio, 0.1, 1000);
                        camera.position.z = 5;

                        // Renderer
                        renderer = new THREE.WebGLRenderer();
                    const width = 500; // Adjust width as needed
                    const height = 500; // Adjust height as needed
                    renderer.setSize(width, height);
                    document.body.appendChild(renderer.domElement);

                    // OrbitControls
                    controls = new THREE.OrbitControls(camera, renderer.domElement);

                    // Pyramid
                    const pyramidGeometry = new THREE.ConeGeometry(1, 1.5, 4);
                    const pyramidMaterial = new THREE.MeshBasicMaterial({ color: 0x808080 });
                    const pyramid = new THREE.Mesh(pyramidGeometry, pyramidMaterial);
                    scene.add(pyramid);
                    objectToRotate = pyramid;

                    //Light
                    const ambient = new THREE.AmbientLight(0xffffff, 1); // Fixed typo here
                    scene.add(ambient);

                    let light = new THREE.PointLight(0xc4c4c4,1);
                    light.position.set(0, 300, 500);
                    scene.add(light);

                    let light2 = new THREE.PointLight(0xc4c4c4,1);
                    light2.position.set(500, 300, 500);
                    scene.add(light2);

                    // Resize
                    window.addEventListener('resize', onWindowResize);

                    // Mouse events
                    document.addEventListener('mousedown', onMouseDown);
                    document.addEventListener('mousemove', onMouseMove);
                    document.addEventListener('mouseup', onMouseUp);

                    {% if format == 'gltf' %}
                    const gltfLoader = new THREE.GLTFLoader();
                    gltfLoader.load(
                        '{{ work.file_model.url }}',
                        function (gltf) {
                            scene.remove(pyramid);
                            objectToRotate = gltf.scene;
                            scene.add(objectToRotate);
                        },
                        function (xhr) {
                            console.log('GLTF model ' + (xhr.loaded / xhr.total * 100) + '% loaded');
                        },
                        function (error) {
                            console.error('Error loading GLTF model:', error);
                        }
                    );
                    {% endif %}

                    {% if format == '.fbx' %}
                    // Load FBX Model
                    const fbxLoader = new THREE.FBXLoader();
                    fbxLoader.load(
                        '{{ work.file_model.url }}',
                        function (object) {
                            scene.remove(pyramid);
                            objectToRotate = object;
                            scene.add(objectToRotate);
                        },
                        function (xhr) {
                            console.log('FBX model ' + (xhr.loaded / xhr.total * 100) + '% loaded');
                        },
                        function (error) {
                            console.error('Error loading FBX model:', error);
                        }
                    );
                    {% endif %}

                    {% if format == '.obj' %}
                    // Load OBJ Model
                    const objLoader = new THREE.OBJLoader();
                    objLoader.load(
                    '{{ work.file_model.url }}',
                    function (obj) {
                        scene.remove(pyramid);
                        objectToRotate = obj;
                        scene.add(objectToRotate);
                    },
                    function (xhr) {
                        console.log('OBJ model ' + (xhr.loaded / xhr.total * 100) + '% loaded');
                    },
                    function (error) {
                        console.error('Error loading OBJ model:', error);
                    }
                    );
                    {% endif %}

                    {% if format == '.dae' %}
                    // Load Collada Model
                    const colladaLoader = new THREE.ColladaLoader();
                    colladaLoader.load(
                        '{{ work.file_model.url }}',
                        function (collada) {
                            scene.remove(pyramid);
                            objectToRotate = collada.scene;
                            scene.add(objectToRotate);
                        },
                        function (xhr) {
                            console.log('Collada model ' + (xhr.loaded / xhr.total * 100) + '% loaded');
                        },
                        function (error) {
                            console.error('Error loading Collada model:', error);
                        }
                    );
                    {% endif %}
                }

                function onWindowResize() {
                    const aspectRatio = 1; // Aspect ratio 1:1
                    camera.aspect = aspectRatio;
                    camera.updateProjectionMatrix();
                    renderer.setSize(500, 500); // Size 500x500
                }

                function onMouseDown(event) {
                    controls.enabled = false;
                }

                function onMouseMove(event) {
                    // Rotate
                    if (controls.enabled === false) {
                        const deltaX = event.movementX || event.mozMovementX || event.webkitMovementX || 0;
                        const deltaY = event.movementY || event.mozMovementY || event.webkitMovementY || 0;
                        objectToRotate.rotation.y -= deltaX * 0.01;
                        objectToRotate.rotation.x -= deltaY * 0.01;
                    }
                }

                function onMouseUp(event) {
                    controls.enabled = true;
                }

                function animate() {
                    requestAnimationFrame(animate);
                    controls.update();
                    renderer.render(scene, camera);
                }
            </script>
            </div>
        </div>

        <! ПРАВАЯ СТОРОНА -->
        <div class="Ramka1 dop2 not_Ramka1 not_background-image" style="margin-right:-500px;" >
            <u><b>Оценки</b></u><br>
            {% for teacher in teachers %}
            <div class="header_lag  widht_95  Ellipse1">
                <div id="Div11">
                    {{ teacher.first_name }} {{ teacher.last_name }}
                </div>
                <form action="{% url 'classrooms:work_big' author_login=a_l classroom_key=c_k work_pk=work.pk %}" method="POST">
                    {% csrf_token %}
                    {% if not m and user.roles == 'teacher' and user.username == teacher.username %}
                    <div>
                    {{ form.value }}
                    <input type = "submit" value = "Выставить">
                    </div>
                    {% else %}
                    {% for ms in m1 %}
                        {% if ms.teacher == teacher.username %}
                <div id="Div12">
                    {{ ms.value }}
                </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </form>
            </div>
            {% endfor %}
            <div class="header_lag  widht_95  Ellipse1">
                    <div id="Div13">Средний балл:</div>
                    <div id="Div14">{{ work_medium_mark }}</div>
            </div>
            <a href="{% url 'classrooms:download' work_pk %}" class="favorite styled" type="button" style="text-decoration:none;">Скачать</a>
        {% if user == author %}
        <a href="{% url 'classrooms:delete' work_id=work_pk cl_k=c_k %}" class="favorite styled" type="button" style="text-decoration:none;">Удалить</a>
        {% endif %}
        </div>
    </CENTER>

{% endblock %}