Backend/VisualSculptingClassroom/VisualSculptingClassroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('users/', include('users.urls', namespace='users')),
    path('classrooms/', include('classrooms.urls', namespace='classrooms')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/VisualSculptingClassroom/users/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import login, registration, logout, profile
app_name = 'users'

urlpatterns = [
    path('login/', login, name = 'login'),
    path('registration/', registration, name = 'registration'),
    path('logout/', logout, name= 'logout'),
    path('profile/<int:user_id>/', profile, name='profile'),
]

Backend/VisualSculptingClassroom/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    role = (
        ('student', "Ученик"),
        ('teacher', "Преподаватель")
    )
    roles = models.CharField(max_length=20, choices=role, default="student")

Backend/VisualSculptingClassroom/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from users.models import User

class UserLoginForm(AuthenticationForm):
    username =  forms.CharField(widget=forms.TextInput(attrs={
        'type' : 'text',
        'name' : "text_name",
        'placeholder' : "Логин",
        "style": "width: 90%; line-height: 28px; ",
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'type' : 'password',
        'name' : "text_name",
        'placeholder' : "Пароль",
        "style": "width: 90%; line-height: 28px; ",
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        "type" : "text",
        "name" : "text_name",
        "placeholder" : "Имя",
        "style" : "width: 90%; line-height: 28px; "
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        "type": "text",
        "name": "text_name",
        "placeholder": "Фамилия",
        "style": "width: 90%; line-height: 28px; "
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        "type": "text",
        "name": "text_name",
        "placeholder": "Логин",
        "style": "width: 90%; line-height: 28px; "
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "type": "password",
        "name": "text_name",
        "placeholder": "Пароль",
        "style": "width: 90%; line-height: 28px; "
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "type": "password",
        "name": "text_name",
        "placeholder": "Подтверждение пароля",
        "style": "width: 90%; line-height: 28px; "
    }))
    roles = forms.Select(attrs={
        "font-size":"15px",
    })
    class Meta:
        model = User
        fields = ('first_name','last_name', 'username', 'password1', 'password2', 'roles')
class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'type':'text',
        'name':'text_name',
        'placeholder':'Изменить имя',
        'style':'width: 50%; line-height: 28px;'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'name': 'text_name',
        'placeholder': 'Изменить фамилию',
        'style': 'width: 50%; line-height: 28px;',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'readonly': True,
        'type': 'text',
        'name': 'text_name',
        'style': 'width: 50%; line-height: 28px;',
    }))
    roles = forms.CharField(widget=forms.TextInput({
        'readonly': True,
        'type': 'text',
        'name': 'text_name',
        'style': 'width: 50%; line-height: 28px;'
    }))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'roles')

Backend/VisualSculptingClassroom/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
# Create your views here.

def index(request):
    context = {
        'title': 'VisualSculptingClassroom',
    }
    return render(request, 'users/index.html', context)

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password = password)
            if user:
                auth.login(request,user)
                return HttpResponseRedirect(reverse('classrooms:classrooms_list'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Вход',
        'form': form,
    }
    return render(request, 'users/login.html', context)
def registration(request):
    if request.method == 'POST':
        i_d = {'last_name':'ddd'}
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Поздравляем! Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {
        'form' : form,
        'title': 'Регистрация'
    }
    return render(request, 'users/registration.html', context)
@login_required

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

def profile(request, user_id):
    if request.method == "POST":
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)


    context ={
        'title':'Профиль',
        'form':form,
        'user': request.user
    }
    return render(request, 'users/profile.html', context)

Backend/VisualSculptingClassroom/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="utf-8" />
	<title>{{ title }}</title>
	<link type="text/css" rel="stylesheet" href="{% static 'css/1.css' %}">
</head>
<body vlink="#003366">

	<div class="header_lag">

		<div id="buttonsleft">
                    Virtual Sculpting Classroom
		</div>
		<div id="buttonsright">
			<a href='{% url "users:login" %}'>Войти | Зарегистрироваться</a>
		</div>

	</div>

	{% block content %}
    {% endblock %}
</body>
</html>

Backend/VisualSculptingClassroom/users/templates/users/index.html
{% extends 'users/base.html' %}

{% block content %}
<h1>
    Начни свой путь в дизайне
</h1>

<div class="textBlock">
    <B>Virtual Sculpting Classroom - виртуальное пространство, созданное для комфортного обучения и развития собственных навыков в сфере дизайна.</B>
</div>
{% endblock %}

Backend/VisualSculptingClassroom/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{{ title }}</title>

    <LINK TYPE="text/css" REL="stylesheet" HREF="{% static 'css/1.css' %}">
</head>
<body vlink="#003366">

    <div class="header_lag">
		<div id="buttonsleft">
                    Virtual Sculpting Classroom
		</div>
		<div id="buttonsright">
			<a href='{% url "index" %}'>На главную страницу</a>
		</div>
	</div>
        <form action="{% url 'users:login' %}" method='post'>
        {% csrf_token %}
        {% if messages or form.non_field_errors %}
            <CENTER>
                <div class="rectangle Ellipse1" style="margin-top:-60px; width: 300px; background-color:rgb(224,176,255); padding: 20px; text-align: left; color: blueviolet;">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %}
                </div>
            </CENTER>
        {% endif %}
        <div class="Ramka1" style="margin-top:30px;">
            <B><p>Вход</p></B>
            {{ form.username }}
            {{ form.password }}
            <p><button class="favorite styled" type="submit">Войти</button></p>
            <a href = '{% url "users:registration" %}'>Регистрация </a>
        </div>
        </form>
</body>
</html>

Backend/VisualSculptingClassroom/users/templates/users/profile.html
{% extends 'classrooms/base.html' %}

{% block content %}
<form action="{% url 'users:profile' user.pk %}" method = 'post' enctype="multipart/form-data">
    {% csrf_token %}
    <div class="Ramka1" >
        <B> <p style="margin-bottom: 0px " >Данные профиля</p>
        <p class="m2" style="margin-top: -15px; margin-bottom: -50px; font-size: 18px;">Имя:</p>
        {{ form.first_name }}
        <p class="m2" style="margin-top: 0px; margin-bottom: -50px;font-size: 18px ">Фамилия:</p>
        {{ form.last_name }}
        <p class="m2" style="margin-top: 0px; margin-bottom: -50px;font-size: 18px">Логин:</p>
        {{ form.username }}
        <p class="m2" style="margin-top: 0px; margin-bottom: -50px;font-size: 18px">Вы:</p>
        <p style ="font-size:18px;">{{ user.get_roles_display }}</p>
        </B>
        <p><input class="favorite styled" type="submit" value="Изменить"></button></p>
    </div>
</form>
{% endblock %}

Backend/VisualSculptingClassroom/users/templates/users/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <title> {{ title }} </title>
    <LINK TYPE="text/css" REL="stylesheet" HREF="{% static 'css/1.css' %}">
</head>
<body vlink="#003366">
    <div class="header_lag">
		<div id="buttonsleft">
                    Virtual Sculpting Classroom
		</div>
		<div id="buttonsright">
			<a href='{% url "index"%}'>На главную страницу</a>
		</div>
	</div>
    <form action = "{% url 'users:registration' %}" method = "post">
        {% csrf_token %}
        {% if form.errors %}
            <CENTER>
                <div class="rectangle Ellipse1" style="margin-top:-60px; width: 300px; background-color:rgb(224,176,255); padding: 20px; text-align: left; color: blueviolet;">
                    {{ form.errors }}
                </div>
            </CENTER>
        {% endif %}
        <div class="Ramka1" style="margin-top:30px;">
            <B>Регистрация</B>
            {{ form.first_name }}
            {{ form.last_name }}
            {{ form.username }}
            {{ form.password1 }}
            {{ form.password2 }}
            <label for="{{ form.roles.id_for_label }}" style="color:blueviolet; font-size:20px">Вы </label>
            {{ form.roles }}
            <p><button class="favorite styled" type="submit">Зарегистрироваться</button></p>
            <a color = "blueviolet" href = "{% url 'users:login' %}">Вход</a>
        </div>
    </form>
</body>
</html>